_target_: src.logger.CometMLWriter
project_name: "lenless-camera"
workspace: null
run_name: "le_admm20"
mode: "online"
loss_names: ["loss", "mse_loss", "lpips_loss"]
log_checkpoints: False
id_length: 32
